//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guestbook
    {
        public int IdGuestbook { get; set; }
        public string Message { get; set; }
        public string Guestname { get; set; }
        public System.DateTime DataInsert { get; set; }
        public bool Visibile { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
    }
}
