//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVP
    {
        public int IdRsvp { get; set; }
        public string Guid { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int Esito { get; set; }
        public bool SpecialMenu { get; set; }
        public string Notes { get; set; }
        public System.DateTime DataInsert { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public bool ConsensoPrivacy { get; set; }
    }
}
